<?php
/**
 * @file
 * A module that provides charts for family tree information
 */

/**
 * Implements hook_help().
 *
 * Displays help and module information.
 *
 * @param path 
 *   Which path of the site we're using to display help
 * @param arg 
 *   Array that holds the current path as returned from arg() function
 */
function family_charts_help($path, $arg){
	switch($path) {
		case "admin/family_charts":
			return '<p>' . t("Provides charts for family tree information.") . '</p>';
			break;
	}
}
 
/**
 * Implements hook_menu().
 *
 * Defines a path for a new page in Drupal
 */
function family_charts_menu() 
{
	$items['family_charts/direct'] = array(
		'title' => 'Direct Ancestors',
		'page callback' => 'family_charts_direct',
		'access arguments' => array('access content'),
	);
 
	return $items;
}

/**
* Custom content function
* 
* Retrieves direct ancestor data
*
* @return
* 	A result set of direct ancestors
*/
function family_charts_contents() {
	$query= db_select('node', 'n')
			->fields('n', array('nid', 'title'))
			->condition('type', 'person') // person
			->orderBy('created', 'DESC') //Most recent first.
			->execute(); 
			
	return $query; 
}
 
 /**
* Custom callback function.
*/
function family_charts_direct() {
	// Custom function to retrieve data
	$results = family_charts_contents();
		
	// Array to contain items to list on page
	$items = array();
	
	foreach ($results as $result) {
        $items[] = array(
			'data' => t($result->title),
        );
    }
	
	$output = array(
		'#items' => $items,
		'#theme' => 'item_list',
	);
 
	return $output;
}
